# Generated by Django 4.2.29 on 2026-04-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_budges_color_size_product_badges_product_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budges',
            options={'verbose_name': 'Budge', 'verbose_name_plural': 'Budges'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['-size'], 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['size'], name='main_size_size_aeb2b2_idx'),
        ),
    ]
