# Generated by Django 4.2.29 on 2026-04-06 16:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_budges_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=7, samples=None),
        ),
    ]
