# Generated by Django 4.2.29 on 2026-04-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_color_hex_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='main_produc_created_9244ff_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='main_produc_created_276cd8_idx'),
        ),
    ]
