# Generated by Django 4.2.29 on 2026-04-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productimage_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badges',
            field=models.ManyToManyField(blank=True, default='all', related_name='products_by_bages', to='main.budges'),
        ),
    ]
