# Generated by Django 4.2.29 on 2026-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=15)),
                ('discount', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Code',
                'verbose_name_plural': 'Codes',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='main_promoc_code_173cdf_idx')],
            },
        ),
    ]
